[Component]
    Components = [
        { Name = "GLOBAL.SF Tech.Online Store Company.Purchase Processing.Payment Service.paymentservice", Application = "GLOBAL.SF Tech.Online Store Company.Hipster Store.Dev.Hipster Store;Labor Day Sale;1_2_10_2"}
    ]    
    Version = "1.2.2"
    ChartName = "chart/paymentservice"
    DockerRepo = "quay.io/hipsterstore/paymentservice"
    GitUrl = "https://github.com/ortelius/store-paymentservice"
    CustomAction = "GLOBAL.HelmChart"