[Component]
    Name = "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.paymentservice"
    Version = "1.2.2"
    ChartName = "chart/paymentservice"
    DockerRepo = "quay.io/hipsterstore/paymentservice"
    GitUrl = "https://github.com/ortelius/store-paymentservice"
    HelmChart = "GLOBAL.HelmChart"
    Applications = [
        "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.Webstore;July 4th Sale;1.2.9.1"
    ]